---
# Program arguments
resolution: 5000 # resolution of contact map to call dots on
genome: "hg38"

# Chromosight arguments
cs_min_distance: 20000
cs_max_distance: 10000000
cs_percentage_zero: 10
cs_threads: 8
cs_out_prefix: 'chromosight_dots' 

# Mustache arguments
mustache_software: "/mnt/data0/noah/software/mustache/mustache/mustache.py"
m_pThreshold: 0.1 # default = 0.1 - higher for sparse matrices
m_sparsityThreshold: 0.88 # default = 0.88 - lower for high res / sparse matrices
m_out_file: 'mustache_dots.dots'
m_threads: 8

# Dotfinder arguments
# cooltools dotfinder documentation: https://cooltools.readthedocs.io/en/latest/cooltools.html#module-cooltools.api.dotfinder
df_expected_value_column: "balanced.avg" # default = 'balanced.avg'
df_weight_name: "weight" # default = 'weight'
df_max_distance: 10000000 # default = 10000000
df_max_nan: 1 # default = 1
df_num_lambda_bins: 40 # default = 40
df_lambda_bin_fdr: 0.1 # default = 0.1
df_clustering_radius: 20000 # default = 20000
df_tile_size: 5000000 # default = 5000000
df_threads: 8
df_out_file: './dotfinder_dots.dots'
